language: csharp
dist: xenial
mono: 5.20.1
dotnet: none
git:
  depth: false
env:
- DOCFX_TOOL="mono docfx.console/tools/docfx.exe"
install:
- nuget install docfx.console -Version 2.44.0 -ExcludeVersion
script:
- $DOCFX_TOOL metadata docfx.json
- $DOCFX_TOOL build docfx.json
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  repo: fluentmigrator/fluentmigrator.github.io
  target-branch: master
  local-dir: _site
  keep-history: true
  on:
    branch: master
